name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v15
        with:
          name: logos-co
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build design system QML library
        run: nix build --print-build-logs

      - name: Run unit tests
        run: nix build .#checks.x86_64-linux.tests --print-build-logs

      - name: Build storybook
        run: nix build .#storybook --print-build-logs
